### ISSUE TITLE
Atom is freezing on invalid syntax

### ISSUE THREAD

**Issue by xavierfoucrier** [lesshint/atom-linter-lesshint#39]
Since the last update from 5.0.0 to 6.0.0, **Atom is completely freezing** when a syntax problem occur. You can reproduce the bug by creating a less file containing this code:

```
&::before,
&::after {
  content: '';
  position: absolute;
  left: 0;
}
```

When you comment the line `&::after {`, the syntax is now broken and Atom is freezing...
This is a critical bug.

Thanks for your feedback :wink:

**Comment by jwilsson** [comment]
Hi!
Thanks for the report!

I think I've tracked in down to an upstream dependency of `lesshint` (`postcss-selector-parser`) which hangs on invalid selectors. I'll see if the new version of that fixes the issue.

**Comment by jwilsson** [comment]
`linter-lesshint@6.0.1` should fix this issue. If not, please let me know!

**Comment by xavierfoucrier** [comment]
Thanks for the fix, I will try tomorrow and give a feedback soon. 👍

**Comment by xavierfoucrier** [comment]
Hi @jwilsson!

It seem's that the issue is now fixed, big thanks!
:wink: :beers:

**Comment by xavierfoucrier** [comment]
Hi @jwilsson,

Since this fix, the linter is throwing errors, sometimes... here is the detailed error from the Atom developer console:

```
C:\Users\xavier\.atom\packages\linter\lib\linter-registry.js:159
[Linter] Error running lesshint Error: Column start (6) greater than line length (5) for line 21
    at generateRange (C:\Users\xavier\.atom\packages\linter-lesshint\node_modules
    \atom-linter\lib\index.js:181:11)
    at file:///C:/Users/xavier/.atom/packages/linter-lesshint/index.js:96:35
    at Array.map (<anonymous>)
    at Object.<anonymous> (file:///C:/Users/xavier/.atom/packages/linter-lesshint/index.js:90:31)
    at Generator.next (<anonymous>)
    at step (C:\Users\xavier\.atom\packages\linter-lesshint\index.js:9:273)
    at <anonymous>
```

:confused:

**Comment by jwilsson** [comment]
@xavierfoucrier Hmm, do you have some Less code that's always triggering that error?

**Comment by jwilsson** [comment]
@xavierfoucrier I managed to track it down to an issue in `lesshint`, `atom-linter-lesshint@6.0.2` should resolve this issue. Please let me know if it doesn't!

**Comment by xavierfoucrier** [comment]
Fixed! Thanks for the patch :coffee:
