### ISSUE TITLE
Bump version of linter

### ISSUE THREAD

**Issue by puranjayjain** [lesshint/atom-linter-lesshint#6]
Can we please update the lesshint version to the current v1.5.2? 

A suggestion: enable greenkeeper?

I'll be happy to send a PR if changes in the code are required to make that change.

**Comment by puranjayjain** [comment]
@jwilsson can you please look into this?

**Comment by jwilsson** [comment]
I've bumped the `lesshint` version and enabled Greenkeeper.

Will publish a new version momentarily.

**Comment by puranjayjain** [comment]
Thank you ☺
